
const characters = ["Teacher", "Student", "Nurse", "Doctor", "Police Officer", "Firefighter", "Chef", "Baker", "Bus Driver", "Librarian", "Shop Staff", "Office Worker", "Farmer", "Fisherman", "Carpenter", "Hair Stylist", "Musician", "Artist", "Athlete", "Scientist", "Programmer", "Writer", "Astronaut", "Pilot", "Detective", "Spy", "Superhero", "Villain", "Robot", "Alien", "Wizard", "Witch", "Vampire", "Ghost", "Zombie", "Dragon", "Unicorn", "Mermaid", "Fairy", "Cat", "Dog", "Bird", "Fish", "Rabbit", "Hamster", "Turtle", "Frog", "Snake", "Lion", "Elephant", "Giraffe", "Monkey", "Panda", "Bear", "Tiger", "Wolf", "Fox", "Dolphin", "Shark", "Whale", "Penguin", "Owl", "Eagle", "Butterfly", "Spider", "Ant", "Bee", "Ladybug", "Grasshopper", "Tree", "Flower", "Cloud", "Sun", "Moon", "Star", "Mountain", "River", "Ocean", "Volcano", "Earth", "Mars", "Jupiter", "Saturn", "Spaceship", "Time Machine", "Ninja", "Samurai", "Knight", "Pirate", "Cowboy", "King", "Queen", "Prince", "Princess", "Hero", "Heroine", "Villager", "Shopkeeper", "Blacksmith", "Innkeeper", "Bard", "Thief", "Warrior", "Mage", "Healer", "Archer", "Swordsman", "Scientist", "Inventor", "Explorer", "Scholar", "Politician", "Celebrity", "Idol", "Athlete", "Gamer", "YouTuber", "Streamer", "Vlogger", "Blogger", "Cosplayer", "Maid", "Butler", "Chef", "Waitress", "Doctor", "Nurse", "Teacher", "Student", "Salaryman", "OL", "Freeter", "NEET", "Host", "Hostess", "Yakuza", "Police Officer", "Detective", "Lawyer", "Judge", "Pilot", "Flight Attendant", "Train Conductor", "Bus Driver", "Taxi Driver", "Truck Driver", "Delivery Person", "Construction Worker", "Engineer", "Architect", "Designer", "Artist", "Musician", "Writer", "Actor", "Voice Actor", "Comedian", "Model", "Idol", "Singer", "Dancer", "Magician", "Fortune Teller", "Monk", "Priest", "Shrine Maiden", "Miko", "Ghost", "Zombie", "Vampire", "Dragon", "Phoenix", "Kirin", "Kappa", "Tengu", "Oni", "Yokai", "Tanuki", "Kitsune", "Bakeneko", "Yuki-Onna", "Tsuchinoko", "Mermaid", "Angel", "Demon", "God", "Goddess"];

const locations = [
    "Classroom",
    "School library",
    "Cafeteria",
    "School gymnasium",
    "Principal's office",
    "Teacher's lounge",
    "School nurse's office",
    "School bus",
    "Soccer field",
    "Basketball court",
    "Tennis court",
    "Track and field",
    "Swimming pool",
    "Science lab",
    "Computer lab",
    "Art room",
    "Music room",
    "Drama room",
    "Auditorium",
    "Student council room",
    "School rooftop",
    "Park",
    "Playground",
    "Bus stop",
    "Train station",
    "Subway station",
    "Airport",
    "Shopping mall",
    "Grocery store",
    "Convenience store",
    "Restaurant",
    "Cafe",
    "Fast food restaurant",
    "Movie theater",
    "Bowling alley",
    "Arcade",
    "Karaoke room",
    "Library",
    "Museum",
    "Art gallery",
    "Zoo",
    "Aquarium",
    "Botanical garden",
    "Amusement park",
    "Water park",
    "Theme park",
    "Beach",
    "Lake",
    "River",
    "Mountain",
    "Forest",
    "Desert",
    "Camping ground",
    "Hiking trail",
    "Ski resort",
    "Ice skating rink",
    "Hospital",
    "Doctor's office",
    "Dentist's office",
    "Pharmacy",
    "Bank",
    "Post office",
    "Police station",
    "Fire station",
    "City hall",
    "Apartment building",
    "House",
    "Neighborhood",
    "Street corner",
    "Crosswalk",
    "Traffic light",
    "Bridge",
    "Tunnel",
    "Highway",
    "Train tracks",
    "Construction site",
    "Farm",
    "Garden",
    "Greenhouse",
    "Pet store",
    "Bookstore",
    "Clothing store",
    "Music store",
    "Electronics store",
    "Sporting goods store",
    "Toy store",
    "Hair salon",
    "Barber shop",
    "Nail salon",
    "Spa",
    "Gym",
    "Yoga studio",
    "Dance studio",
    "Martial arts studio",
    "Coffee shop",
    "Bakery",
    "Ice cream shop",
    "Candy store",
    "Flower shop",
    "Jewelry store",
    "Gift shop",
    "Antique shop",
    "Pawn shop",
    "Thrift store",
    " Flea market",
    "Farmers market",
    "Castle",
    "Palace",
    "Temple",
    "Church",
    "Mosque",
    "Synagogue",
    "Historical monument",
    "Ruins",
    "Graveyard",
    "Haunted house",
    "Spaceship",
    "Space station",
    "Alien planet",
    "Fantasy world",
    "Video game world",
    "Dream world",
    "Time machine",
    "Virtual reality",
    "Another dimension",
    "The past",
    "The future"
];